"""Add portafolio history model

Revision ID: 4ee8ca141669
Revises: e4eae37c05e4
Create Date: 2024-07-19 21:07:34.789195

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ee8ca141669"
down_revision = "e4eae37c05e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portafolio",
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("update_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("portafolio_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("total_euros", sa.Float(), nullable=False),
        sa.Column("total_currency_euros", sa.Float(), nullable=False),
        sa.Column("profit_euros", sa.Float(), nullable=False),
        sa.Column("investment_euros", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.user_id"],
        ),
        sa.PrimaryKeyConstraint("portafolio_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portafolio")
    # ### end Alembic commands ###
